#!/usr/bin/env python3
"""Prepare the generated bytes for one automatic Cargo release.

The release train owns exactly two possible paths:

* the manifest containing the authoritative package/workspace version; and
* an already-tracked root ``Cargo.lock``.

The helper intentionally does not run ``cargo update``.  It changes only
source-less local ``kin-*`` lockfile package records that still carry the
previous workspace version, then asks ``cargo metadata`` to prove that the
requested package resolves to the generated target.  Registry/git source and
checksum lines are treated as immutable input.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable


SEMVER_RE = re.compile(
    r"^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$"
)
VERSION_LINE_RE = re.compile(
    r'^(?P<indent>\s*)version(?P<space>\s*=\s*)"(?P<version>[^"]+)"'
    r"(?P<tail>\s*(?:#.*)?)$"
)
PACKAGE_BLOCK_RE = re.compile(
    r"(?ms)^\[\[package\]\]\r?\n.*?(?=^\[\[package\]\]\r?\n|\Z)"
)
LOCK_NAME_RE = re.compile(r'(?m)^name\s*=\s*"([^"]+)"\s*$')
LOCK_VERSION_RE = re.compile(r'(?m)^version\s*=\s*"([^"]+)"\s*$')
LOCK_SOURCE_RE = re.compile(r'(?m)^source\s*=\s*"([^"]+)"\s*$')
LOCK_CHECKSUM_RE = re.compile(r'(?m)^checksum\s*=\s*"([^"]+)"\s*$')


class ReleasePreparationError(RuntimeError):
    """A fail-closed release preparation error."""


@dataclass(frozen=True, order=True)
class StableVersion:
    major: int
    minor: int
    patch: int

    @classmethod
    def parse(cls, raw: str) -> "StableVersion":
        match = SEMVER_RE.fullmatch(raw.strip())
        if not match:
            raise ReleasePreparationError(
                f"automatic releases require stable numeric SemVer, got {raw!r}"
            )
        return cls(*(int(part) for part in match.groups()))

    def bump(self, intent: str) -> "StableVersion":
        if intent == "patch":
            return StableVersion(self.major, self.minor, self.patch + 1)
        if intent == "minor":
            return StableVersion(self.major, self.minor + 1, 0)
        if intent == "major":
            return StableVersion(self.major + 1, 0, 0)
        raise ReleasePreparationError(
            f"release intent must be patch, minor, or major; got {intent!r}"
        )

    def __str__(self) -> str:
        return f"{self.major}.{self.minor}.{self.patch}"


@dataclass(frozen=True)
class VersionAuthority:
    path: Path
    section: str
    version: StableVersion
    line_index: int
    lines: tuple[str, ...]


def _regular_file(path: Path) -> None:
    if path.is_symlink():
        raise ReleasePreparationError(f"refusing symlink release input: {path}")
    if not path.is_file():
        raise ReleasePreparationError(f"release input is not a regular file: {path}")


def _section_lines(path: Path) -> tuple[list[str], dict[str, list[int]]]:
    _regular_file(path)
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    section = ""
    sections: dict[str, list[int]] = {}
    for index, raw in enumerate(lines):
        stripped = raw.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            section = stripped.strip("[]").strip()
            continue
        sections.setdefault(section, []).append(index)
    return lines, sections


def _direct_version(path: Path, section: str) -> VersionAuthority | None:
    lines, sections = _section_lines(path)
    matches: list[tuple[int, StableVersion]] = []
    for index in sections.get(section, []):
        match = VERSION_LINE_RE.match(lines[index].rstrip("\r\n"))
        if match:
            matches.append((index, StableVersion.parse(match.group("version"))))
    if len(matches) > 1:
        raise ReleasePreparationError(
            f"{path}: [{section}] has multiple version authorities"
        )
    if not matches:
        return None
    index, version = matches[0]
    return VersionAuthority(path, section, version, index, tuple(lines))


def find_version_authority(root: Path, manifest: str) -> VersionAuthority:
    manifest_path = (root / manifest).absolute()
    try:
        relative = manifest_path.relative_to(root.resolve())
    except ValueError as exc:
        raise ReleasePreparationError(
            f"manifest escapes repository root: {manifest}"
        ) from exc
    cursor = root.resolve()
    for part in relative.parts:
        cursor = cursor / part
        if cursor.is_symlink():
            raise ReleasePreparationError(f"refusing symlink release input: {cursor}")

    authority = _direct_version(manifest_path, "package")
    if authority is not None:
        return authority

    manifest_text = manifest_path.read_text(encoding="utf-8")
    if not re.search(
        r"(?m)^\s*version\.workspace\s*=\s*true\s*(?:#.*)?$", manifest_text
    ):
        raise ReleasePreparationError(
            f"{manifest}: [package] has neither a direct version nor "
            "version.workspace = true"
        )

    root_manifest = root / "Cargo.toml"
    authority = _direct_version(root_manifest, "workspace.package")
    if authority is None:
        raise ReleasePreparationError(
            "workspace package inherits its version, but root "
            "Cargo.toml has no [workspace.package] version"
        )
    return authority


def _replace_authority(authority: VersionAuthority, target: StableVersion) -> bytes:
    lines = list(authority.lines)
    raw = lines[authority.line_index]
    ending = "\r\n" if raw.endswith("\r\n") else "\n" if raw.endswith("\n") else ""
    match = VERSION_LINE_RE.match(raw.rstrip("\r\n"))
    if not match:
        raise ReleasePreparationError("version authority moved during preparation")
    lines[authority.line_index] = (
        f'{match.group("indent")}version{match.group("space")}"{target}"'
        f'{match.group("tail")}{ending}'
    )
    return "".join(lines).encode("utf-8")


def _lock_external_identity(text: str) -> list[tuple[str, str, str, str]]:
    identity: list[tuple[str, str, str, str]] = []
    for block in PACKAGE_BLOCK_RE.findall(text):
        name = LOCK_NAME_RE.search(block)
        version = LOCK_VERSION_RE.search(block)
        source = LOCK_SOURCE_RE.search(block)
        checksum = LOCK_CHECKSUM_RE.search(block)
        if source or checksum:
            identity.append(
                (
                    name.group(1) if name else "",
                    version.group(1) if version else "",
                    source.group(1) if source else "",
                    checksum.group(1) if checksum else "",
                )
            )
    return identity


def update_local_lock_packages(
    text: str,
    *,
    prior_versions: set[str],
    target: str,
) -> str:
    """Update source-less local Kin package records and nothing external."""

    before_external = _lock_external_identity(text)

    def update(block_match: re.Match[str]) -> str:
        block = block_match.group(0)
        name = LOCK_NAME_RE.search(block)
        version = LOCK_VERSION_RE.search(block)
        if not name or not version:
            return block
        if LOCK_SOURCE_RE.search(block) or LOCK_CHECKSUM_RE.search(block):
            return block
        if not name.group(1).startswith("kin-"):
            return block
        if version.group(1) not in prior_versions:
            return block
        start, end = version.span(1)
        return block[:start] + target + block[end:]

    updated = PACKAGE_BLOCK_RE.sub(update, text)
    if _lock_external_identity(updated) != before_external:
        raise ReleasePreparationError(
            "registry/git lockfile source or checksum identity changed"
        )
    return updated


def _is_git_tracked(root: Path, relative: str) -> bool:
    result = subprocess.run(
        ["git", "ls-files", "--error-unmatch", "--", relative],
        cwd=root,
        text=True,
        capture_output=True,
        check=False,
    )
    return result.returncode == 0


def _cargo_metadata_resolver(
    root: Path, package: str, expected: str, tracked_lock: bool
) -> None:
    lock_path = root / "Cargo.lock"
    lock_existed = lock_path.exists()
    args = ["cargo", "metadata", "--no-deps", "--format-version", "1"]
    if tracked_lock:
        args.append("--locked")
    result = subprocess.run(
        args,
        cwd=root,
        text=True,
        capture_output=True,
        check=False,
    )
    if not lock_existed and lock_path.exists():
        lock_path.unlink()
    if result.returncode != 0:
        raise ReleasePreparationError(
            "cargo metadata rejected generated release bytes:\n"
            + (result.stderr or result.stdout).strip()
        )
    try:
        metadata = json.loads(result.stdout)
        resolved = next(
            item["version"]
            for item in metadata["packages"]
            if item["name"] == package
        )
    except (json.JSONDecodeError, KeyError, StopIteration) as exc:
        raise ReleasePreparationError(
            f"package {package!r} was not present in cargo metadata"
        ) from exc
    if resolved != expected:
        raise ReleasePreparationError(
            f"cargo metadata resolved {package}@{resolved}; expected {expected}"
        )


def prepare_release(
    *,
    root: Path,
    package: str,
    manifest: str,
    base_version: str,
    intent: str,
    tracked: Callable[[Path, str], bool] = _is_git_tracked,
    resolver: Callable[[Path, str, str, bool], None] = _cargo_metadata_resolver,
) -> dict[str, object]:
    root = root.resolve()
    base = StableVersion.parse(base_version)
    requested = base.bump(intent)
    authority = find_version_authority(root, manifest)
    current = authority.version
    valid_successors = {base.bump(level) for level in ("patch", "minor", "major")}

    if current == base:
        target = requested
    elif current not in valid_successors:
        raise ReleasePreparationError(
            f"authority version {current} is neither base {base} nor one of its "
            "automatic successors"
        )
    else:
        # A queued stale run must never turn an already-escalated train back
        # into a patch release.
        target = max(current, requested)

    lock_relative = "Cargo.lock"
    lock_path = root / lock_relative
    tracked_lock = tracked(root, lock_relative)
    if tracked_lock:
        _regular_file(lock_path)
    elif lock_path.exists():
        raise ReleasePreparationError(
            "Cargo.lock exists but is not tracked; refusing ambiguous generated input"
        )

    originals: dict[Path, bytes] = {authority.path: authority.path.read_bytes()}
    if tracked_lock:
        originals[lock_path] = lock_path.read_bytes()

    try:
        authority.path.write_bytes(_replace_authority(authority, target))
        if tracked_lock:
            lock_text = originals[lock_path].decode("utf-8")
            updated = update_local_lock_packages(
                lock_text,
                prior_versions={str(base), str(current)},
                target=str(target),
            )
            lock_path.write_text(updated, encoding="utf-8")
        resolver(root, package, str(target), tracked_lock)
    except BaseException:
        for path, data in originals.items():
            path.write_bytes(data)
        raise

    generated = [
        str(path.relative_to(root))
        for path, original in originals.items()
        if path.read_bytes() != original
    ]
    result: dict[str, object] = {
        "package": package,
        "base_version": str(base),
        "previous_generated_version": str(current),
        "target_version": str(target),
        "tag": f"v{target}",
        "intent": (
            "major"
            if target == base.bump("major")
            else "minor"
            if target == base.bump("minor")
            else "patch"
        ),
        "generated_paths": sorted(generated),
        "allowed_paths": sorted(
            {
                str(authority.path.relative_to(root)),
                *([lock_relative] if tracked_lock else []),
            }
        ),
    }
    return result


def inspect_release_inputs(
    *,
    root: Path,
    manifest: str,
    tracked: Callable[[Path, str], bool] = _is_git_tracked,
) -> dict[str, object]:
    """Resolve the exact generated allowlist without modifying the checkout."""

    root = root.resolve()
    authority = find_version_authority(root, manifest)
    lock_relative = "Cargo.lock"
    tracked_lock = tracked(root, lock_relative)
    if tracked_lock:
        _regular_file(root / lock_relative)
    elif (root / lock_relative).exists():
        raise ReleasePreparationError(
            "Cargo.lock exists but is not tracked; refusing ambiguous generated input"
        )
    allowed = [str(authority.path.relative_to(root))]
    if tracked_lock:
        allowed.append(lock_relative)
    return {
        "authority_path": str(authority.path.relative_to(root)),
        "current_version": str(authority.version),
        "tracked_lock": tracked_lock,
        "allowed_paths": sorted(allowed),
    }


def _write_outputs(result: dict[str, object]) -> None:
    output = os.environ.get("GITHUB_OUTPUT")
    if not output:
        return
    with open(output, "a", encoding="utf-8") as stream:
        for key in (
            "base_version",
            "previous_generated_version",
            "target_version",
            "tag",
            "intent",
        ):
            stream.write(f"{key}={result[key]}\n")
        stream.write(
            "generated_paths="
            + " ".join(str(item) for item in result["generated_paths"])
            + "\n"
        )
        stream.write(
            "allowed_paths="
            + " ".join(str(item) for item in result["allowed_paths"])
            + "\n"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="prepare one fail-closed automatic Cargo release"
    )
    parser.add_argument("--package")
    parser.add_argument("--manifest", default="Cargo.toml")
    parser.add_argument("--base-version")
    parser.add_argument("--intent", choices=("patch", "minor", "major"), default="patch")
    parser.add_argument("--root", type=Path, default=Path("."))
    parser.add_argument(
        "--inspect",
        action="store_true",
        help="print exact version authority/generated allowlist without writing",
    )
    args = parser.parse_args(argv)
    try:
        if args.inspect:
            result = inspect_release_inputs(
                root=args.root,
                manifest=args.manifest,
            )
        else:
            if not args.package or not args.base_version:
                parser.error("--package and --base-version are required without --inspect")
            result = prepare_release(
                root=args.root,
                package=args.package,
                manifest=args.manifest,
                base_version=args.base_version,
                intent=args.intent,
            )
    except ReleasePreparationError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    if not args.inspect:
        _write_outputs(result)
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
