#!/usr/bin/env bash
set -euo pipefail

# Advance one generated-only release branch to an exact trusted main commit.
#
# The general release App has Contents + Pull requests only. If main changed a
# workflow while the branch was open, a normal bot push of a merge commit would
# be rejected for lacking Workflows permission. We therefore:
#   1. prove the branch has generated-only tree drift;
#   2. neutralize generated bytes to trusted main and push that safe commit;
#   3. ask GitHub to merge main server-side with POST /merges; and
#   4. validate the returned parents and complete tree before regeneration.
#
# Required environment:
#   GH_TOKEN, GITHUB_REPOSITORY, MAIN_SHA, MAIN_BRANCH, TRAIN_BRANCH,
#   KIN_RELEASE_RECONCILE_SCRIPT
#
# Positional arguments are the exact generated-path allowlist.

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"
: "${MAIN_SHA:?MAIN_SHA is required}"
: "${MAIN_BRANCH:?MAIN_BRANCH is required}"
: "${TRAIN_BRANCH:?TRAIN_BRANCH is required}"
: "${KIN_RELEASE_RECONCILE_SCRIPT:?KIN_RELEASE_RECONCILE_SCRIPT is required}"

if [[ "$GITHUB_REPOSITORY" != */* || "$GITHUB_REPOSITORY" == *[!A-Za-z0-9._/-]* ]]; then
  echo "invalid GITHUB_REPOSITORY: $GITHUB_REPOSITORY" >&2
  exit 1
fi
if [[ ! "$MAIN_SHA" =~ ^[0-9a-f]{40}$ && ! "$MAIN_SHA" =~ ^[0-9a-f]{64}$ ]]; then
  echo "MAIN_SHA must be a full lowercase object ID" >&2
  exit 1
fi
if [[ ! "$MAIN_BRANCH" =~ ^[A-Za-z0-9._/-]+$ ]]; then
  echo "unsafe main branch: $MAIN_BRANCH" >&2
  exit 1
fi
if [[ ! "$TRAIN_BRANCH" =~ ^automation/[A-Za-z0-9._/-]+$ ]]; then
  echo "release train branch must be under automation/: $TRAIN_BRANCH" >&2
  exit 1
fi
if [[ ! -f "$KIN_RELEASE_RECONCILE_SCRIPT" ]]; then
  echo "release reconciliation helper not found" >&2
  exit 1
fi
if (($# == 0)); then
  echo "at least one generated path is required" >&2
  exit 1
fi

generated_args=()
for path in "$@"; do
  generated_args+=(--generated-path "$path")
done

if [[ -n "$(git status --porcelain=v1 --untracked-files=all)" ]]; then
  echo "release checkout must be clean before branch reconciliation" >&2
  exit 1
fi

plain_remote="https://github.com/${GITHUB_REPOSITORY}.git"
token_remote="https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
git remote set-url origin "$token_remote"
restore_remote() {
  git remote set-url origin "$plain_remote" 2>/dev/null || true
}
trap restore_remote EXIT

git fetch --no-tags origin \
  "refs/heads/${MAIN_BRANCH}:refs/remotes/kin-release/trusted-main"
fetched_main="$(git rev-parse refs/remotes/kin-release/trusted-main)"
if [[ "$fetched_main" != "$MAIN_SHA" ]]; then
  echo "trusted main moved from $MAIN_SHA to $fetched_main; refusing stale generation" >&2
  exit 1
fi

matching="$(
  gh api "repos/${GITHUB_REPOSITORY}/git/matching-refs/heads/${TRAIN_BRANCH}"
)"
train_ref="refs/heads/${TRAIN_BRANCH}"
train_sha="$(
  jq -r --arg ref "$train_ref" \
    '[.[] | select(.ref == $ref)][0].object.sha // ""' <<<"$matching"
)"

if [[ -z "$train_sha" ]]; then
  jq -n --arg ref "$train_ref" --arg sha "$MAIN_SHA" \
    '{ref:$ref,sha:$sha}' \
    | gh api --method POST "repos/${GITHUB_REPOSITORY}/git/refs" --input - \
      >/dev/null
  train_sha="$MAIN_SHA"
fi
if [[ ! "$train_sha" =~ ^[0-9a-f]{40}$ && ! "$train_sha" =~ ^[0-9a-f]{64}$ ]]; then
  echo "remote train ref returned malformed object ID" >&2
  exit 1
fi

git fetch --no-tags origin \
  "refs/heads/${TRAIN_BRANCH}:refs/remotes/kin-release/train"
fetched_train="$(git rev-parse refs/remotes/kin-release/train)"
if [[ "$fetched_train" != "$train_sha" ]]; then
  echo "train branch moved while it was being admitted" >&2
  exit 1
fi
git switch --detach "$train_sha"
git switch -c kin-release-train-local

validation="$(
  python3 "$KIN_RELEASE_RECONCILE_SCRIPT" validate-train \
    --trusted-main "$MAIN_SHA" \
    --train-head "$train_sha" \
    "${generated_args[@]}"
)"

if ! git merge-base --is-ancestor "$MAIN_SHA" "$train_sha"; then
  delta_count="$(jq '.changed_paths | length' <<<"$validation")"
  git config user.name "kin-release[bot]"
  git config user.email "kin-release[bot]@users.noreply.github.com"
  if ((delta_count > 0)); then
    python3 "$KIN_RELEASE_RECONCILE_SCRIPT" neutralize \
      --trusted-main "$MAIN_SHA" \
      --old-train-head "$train_sha" \
      "${generated_args[@]}" \
      >/dev/null
    git commit -s -m "chore(release): neutralize generated train bytes"
  else
    # A previous run can create the branch and fail before generation. Give
    # GitHub a distinct Contents-only parent so POST /merges returns the exact
    # two-parent commit that the invariant validator requires.
    git commit --allow-empty -s -m "chore(release): checkpoint release train"
  fi
  neutralized_head="$(git rev-parse HEAD)"
  git push origin "HEAD:refs/heads/${TRAIN_BRANCH}"

  merge_response="$(
    jq -n --arg base "$TRAIN_BRANCH" --arg head "$MAIN_SHA" \
      --arg message "chore(release): merge trusted ${MAIN_BRANCH}" \
      '{base:$base,head:$head,commit_message:$message}' \
      | gh api --method POST "repos/${GITHUB_REPOSITORY}/merges" --input -
  )"
  merge_sha="$(jq -r '.sha // ""' <<<"$merge_response")"
  if [[ ! "$merge_sha" =~ ^[0-9a-f]{40}$ && ! "$merge_sha" =~ ^[0-9a-f]{64}$ ]]; then
    echo "GitHub POST /merges did not return an exact merge commit" >&2
    exit 1
  fi

  matching="$(
    gh api "repos/${GITHUB_REPOSITORY}/git/matching-refs/heads/${TRAIN_BRANCH}"
  )"
  remote_after="$(
    jq -r --arg ref "$train_ref" \
      '[.[] | select(.ref == $ref)][0].object.sha // ""' <<<"$matching"
  )"
  if [[ "$remote_after" != "$merge_sha" ]]; then
    echo "train ref is $remote_after after POST /merges, expected $merge_sha" >&2
    exit 1
  fi
  git fetch --no-tags origin \
    "refs/heads/${TRAIN_BRANCH}:refs/remotes/kin-release/server-merge"
  if [[ "$(git rev-parse refs/remotes/kin-release/server-merge)" != "$merge_sha" ]]; then
    echo "fetched server merge does not match GitHub response" >&2
    exit 1
  fi
  git switch --detach "$merge_sha"
  git branch -f kin-release-train-local "$merge_sha"
  git switch kin-release-train-local
  python3 "$KIN_RELEASE_RECONCILE_SCRIPT" validate-merge \
    --merge-commit "$merge_sha" \
    --old-train-head "$neutralized_head" \
    --trusted-main "$MAIN_SHA" \
    "${generated_args[@]}" \
    >/dev/null
  train_sha="$merge_sha"
fi

restore_remote
trap - EXIT

if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
  {
    echo "train_branch=$TRAIN_BRANCH"
    echo "train_head=$(git rev-parse HEAD)"
    echo "trusted_main=$MAIN_SHA"
  } >> "$GITHUB_OUTPUT"
fi
echo "release train ready at $(git rev-parse HEAD) for trusted main $MAIN_SHA"
