#!/usr/bin/env python3
"""Unit tests for the public metadata safety gate.

Run with: ``python3 -m unittest discover -s scripts -p 'test_*.py'``

Covers the pure detectors with no git / network access. This exact file is
excluded from the gate's own content scan because it intentionally contains
the very patterns the gate rejects.
"""
import contextlib
import importlib.util
import io
import unittest
from unittest import mock
from pathlib import Path


def _load(name, filename):
    path = Path(__file__).resolve().parent / filename
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


hh = _load("history_hygiene", "history-hygiene.py")


class PrivateMetadata(unittest.TestCase):
    def test_detects_session_trailer(self):
        self.assertTrue(hh.scan_private_metadata("fix bug\n\nClaude-Session: https://x/y"))
        self.assertTrue(hh.scan_private_metadata("Codex-Session: abc"))

    def test_detects_assistant_url_and_session_id(self):
        self.assertTrue(
            hh.scan_private_metadata("see https://claude.ai/code/session_0123456789abcdef01"))
        self.assertTrue(
            hh.scan_private_metadata("see https://chatgpt.com/share/0123456789abcdef"))
        self.assertTrue(hh.scan_private_metadata("ref session_0123456789abcdefAB"))

    def test_clean_message_passes(self):
        self.assertEqual(hh.scan_private_metadata("fix: handle empty input in parser"), [])
        self.assertEqual(hh.scan_private_metadata("Signed-off-by: Dev <dev@example.com>"), [])

    def test_former_authorship_markers_are_out_of_scope(self):
        self.assertEqual(hh.scan_private_metadata(
            "Co-authored-by: Claude <noreply@anthropic.com>"), [])
        self.assertEqual(hh.scan_private_metadata("Generated by Codex"), [])
        self.assertEqual(hh.scan_private_metadata("🤖 Generated with Claude Code"), [])
        self.assertEqual(hh.scan_private_metadata("AI-Generated-by: Copilot"), [])
        self.assertEqual(hh.scan_private_metadata("Assisted-by: ChatGPT"), [])


class TicketRefBoundary(unittest.TestCase):
    """The tracker rule is scoped by whether the text becomes a commit message.

    Reversed on 2026-08-05 for anything that does: naming the tickets a merge
    resolves is intended, hundreds of commits on public default branches already
    carry those refs, and barring them made the rule forbid its own output on a
    queue-managed repository. Added content and branch names become no commit
    message and keep the rule.

    Both sides are asserted at every surface. A test that only checked the
    allowed side would pass equally if the rule had been dropped everywhere,
    which is the failure this whole class of bug is made of.
    """

    ALLOWED = "Closes FIR-1965"
    LINK = "https://linear.app/firelock-ai/issue/abc"

    def test_allowed_where_the_text_becomes_a_commit_message(self):
        self.assertEqual(hh.scan_title("Fix the parser (FIR-1234)"), [])
        self.assertEqual(hh.scan_body("Closes FIR-1965\nCloses FIR-1973"), [])
        self.assertEqual(hh.scan_title(self.LINK), [])
        self.assertEqual(hh.scan_body(self.LINK), [])
        # Commit messages run through scan_private_metadata alone.
        self.assertEqual(hh.scan_private_metadata("See FIR-1234 for context"), [])

    def test_rejected_where_it_does_not(self):
        self.assertIn("internal ticket ref (FIR-...)",
                      hh.scan_added_line("// TODO see FIR-9001"))
        self.assertIn("internal tracker link (linear.app)",
                      hh.scan_added_line(f"// see {self.LINK}"))
        # Assert the label rather than truthiness. `assertTrue` on a list passes
        # for any non-empty result, so it would survive the tracker label being
        # replaced by an unrelated one.
        self.assertEqual(
            hh.scan_branch_name("troy/fir-1015-consistent-release"),
            ["branch 'troy/fir-1015-consistent-release' contains "
             "internal ticket ref (FIR-...)"])
        self.assertEqual(
            hh.scan_branch_name(self.LINK),
            [f"branch '{self.LINK}' contains internal tracker link (linear.app)"])

    def test_clean_text_passes(self):
        self.assertEqual(hh.scan_ticket_refs("ordinary changelog text, no refs"), [])
        # A bare word that merely contains the letters must not match.
        self.assertEqual(hh.scan_ticket_refs("CONFIRMED and AFFIRMED"), [])
        self.assertEqual(hh.scan_added_line("let total = a + b; // sum"), [])
        self.assertEqual(hh.scan_branch_name("ci/public-history-hygiene"), [])


class BranchAndTitle(unittest.TestCase):
    def test_branch_private_references(self):
        self.assertTrue(hh.scan_branch_name("fix/session_0123456789abcdef"))

    def test_clean_branch_passes(self):
        self.assertEqual(hh.scan_branch_name("ci/public-history-hygiene"), [])
        self.assertEqual(hh.scan_branch_name("automation/kin-registry-dependency-wave"), [])

    def test_title_leaks(self):
        self.assertTrue(hh.scan_title(
            "See https://chatgpt.com/share/0123456789abcdef"))

    def test_clean_title_passes(self):
        self.assertEqual(hh.scan_title("ci(version-gate): scope bump requirement"), [])

    def test_body_leaks(self):
        self.assertTrue(hh.scan_body(
            "## Change\n\nRework the parser.\n\n"
            "Claude-Session: https://claude.ai/code/session_0123456789abcdef01"))
        self.assertTrue(hh.scan_body(
            "See https://chatgpt.com/share/0123456789abcdef"))
        self.assertTrue(hh.scan_body("ref session_0123456789abcdefAB"))

    def test_clean_body_passes(self):
        self.assertEqual(hh.scan_body(
            "## Change\n\nHandle empty input at the parser boundary.\n\n"
            "## Acceptance\n\npython3 -m unittest discover -s scripts"), [])
        self.assertEqual(hh.scan_body(""), [])
        self.assertEqual(hh.scan_body(None), [])

    def test_a_doctrine_correct_body_passes_whole(self):
        # Exactly what doctrine asks a PR body to carry. This is the case that
        # ejected a PR from the merge queue twice before the rule was reversed.
        self.assertEqual(hh.scan_body(
            "## Change\n\nRework the parser.\n\nCloses FIR-1965\nCloses FIR-1973"), [])


class AddedLineContent(unittest.TestCase):
    def test_detects_refs_and_traces(self):
        self.assertTrue(hh.scan_added_line("# Claude-Session: zzz"))
        self.assertTrue(hh.scan_added_line(
            "// see https://claude.ai/code/session_0123456789abcdef01"))

    def test_clean_code_passes(self):
        self.assertEqual(hh.scan_added_line("let total = a + b; // sum"), [])
        self.assertEqual(hh.scan_added_line("// Generated by a code assistant"), [])


class Excludes(unittest.TestCase):
    def test_default_excludes(self):
        ex = hh.DEFAULT_CONTENT_EXCLUDES
        self.assertTrue(hh.is_excluded("scripts/history-hygiene.py", ex))
        self.assertTrue(hh.is_excluded("scripts/test_history_hygiene.py", ex))

    def test_source_not_excluded(self):
        ex = hh.DEFAULT_CONTENT_EXCLUDES
        self.assertFalse(hh.is_excluded("src/lib.rs", ex))
        self.assertFalse(hh.is_excluded("README.md", ex))
        self.assertFalse(hh.is_excluded(".github/workflows/ci.yml", ex))
        self.assertFalse(hh.is_excluded("CHANGELOG.md", ex))
        self.assertFalse(hh.is_excluded("Cargo.lock", ex))


class GitPlumbing(unittest.TestCase):
    @mock.patch.object(hh.subprocess, "run")
    def test_git_errors_fail_closed(self, run):
        run.return_value = mock.Mock(
            returncode=128,
            stdout="",
            stderr="fatal: bad revision 'missing'",
        )

        with self.assertRaisesRegex(RuntimeError, "bad revision"):
            hh._git(["log", "missing"])

    def test_commit_message_control_separators_cannot_skip_scan(self):
        # The old record/field separators were legal commit-message bytes.
        # NUL is not, so attacker-controlled message bytes cannot forge a
        # record boundary in the scanner's Git format.
        self.assertEqual(hh._REC, "\0\0")
        self.assertEqual(hh._FLD, "\0")

    @mock.patch.object(hh, "_git")
    def test_commit_format_uses_git_nul_escapes_not_argv_nuls(self, git):
        git.return_value = mock.Mock(stdout="")

        self.assertEqual(hh.collect_commits("base", "head"), [])

        args = git.call_args.args[0]
        format_arg = next(arg for arg in args if arg.startswith("--format="))
        self.assertIn("%x00", format_arg)
        self.assertNotIn("\0", format_arg)
        for identity_field in ("%an", "%ae", "%cn", "%ce", "%ct"):
            self.assertNotIn(identity_field, format_arg)


class LegacyOptions(unittest.TestCase):
    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "Generated by a code assistant"}])
    def test_timestamp_option_is_accepted_and_ignored(self, _commits, _lines):
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main([
                "--check-timestamps",
                "--bot-email", "bot@example.com",
                "--tz", "America/New_York",
                "--window-start", "9",
                "--window-end", "18",
            ])
        self.assertEqual(result, 0)
        self.assertIn("legacy timestamp option: ignored", output.getvalue())


class PolicyIntegration(unittest.TestCase):
    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "Add a parser\n\nCloses FIR-123"}])
    def test_commit_message_tracker_ref_passes(self, _commits, _lines):
        # Reversed 2026-08-05. A commit naming the ticket it resolves is the
        # intended shape, and the queue mints exactly this from the PR body.
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main([])
        self.assertEqual(result, 0)
        self.assertIn("OK: no private reference violations found.", output.getvalue())

    @mock.patch.object(hh, "collect_added_lines",
                       return_value=[("src/parser.rs", "// TODO see FIR-1234")])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "Add a parser\n\nCloses FIR-1234"}])
    def test_one_string_four_surfaces_exactly_one_violation(self, _commits, _lines):
        # The single run that pins the scope from both sides at once. The same
        # `FIR-1234` sits in the commit message, the PR title, the PR body, and
        # an added source line. Exactly one of those is a violation.
        #
        # A gate reversed too far reports zero here; a gate not reversed at all
        # reports four. Only the intended boundary reports one, and neither of
        # the wrong answers is distinguishable from the right one without
        # asserting the count.
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main([
                "--title", "Add a parser (FIR-1234)",
                "--body", "Adds a parser.\n\nCloses FIR-1234",
            ])
        printed = output.getvalue()
        self.assertEqual(result, 1)
        self.assertIn("FAIL: 1 metadata safety violation(s):", printed)
        self.assertIn("src/parser.rs: internal ticket ref (FIR-...)", printed)
        self.assertNotIn("PR title contains", printed)
        self.assertNotIn("PR body contains", printed)
        self.assertNotIn("abc123:", printed)

    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{
                           "sha": "abc123",
                           "body": "Add a parser\n\nClaude-Session: https://claude.ai/x",
                       }])
    def test_commit_message_session_trailer_still_fails(self, _commits, _lines):
        # The half that was NOT reversed. Reversing one rule must not quietly
        # relax the other, which shares every call site.
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main([])
        self.assertEqual(result, 1)
        self.assertIn("private metadata", output.getvalue())

    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "add a parser"}])
    def test_body_leak_fails_while_every_commit_is_clean(self, _commits, _lines):
        # The shape of the defect: branch commits, title, and content all pass,
        # and the leak reaches public history through the minted squash alone.
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main([
                "--title", "Add a parser",
                "--body", "Adds a parser.\n\n"
                          "Claude-Session: https://claude.ai/code/session_0123456789abcdef01",
            ])
        self.assertEqual(result, 1)
        self.assertIn("PR body contains private assistant-session metadata",
                      output.getvalue())

    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "add a parser"}])
    def test_absent_body_is_reported_as_unscanned_not_as_clean(self, _commits, _lines):
        # A gate that reports the same thing whether it read an input or never
        # received one cannot be audited. This is the line that would have shown
        # the blind spot at a glance.
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main(["--title", "Add a parser"])
        self.assertEqual(result, 0)
        self.assertIn("body             : <none supplied, not scanned>", output.getvalue())

        scanned = io.StringIO()
        with contextlib.redirect_stdout(scanned):
            hh.main(["--title", "Add a parser", "--body", "Adds a parser."])
        self.assertIn("body             : 14 chars scanned as the squash message",
                      scanned.getvalue())


class AttributionScope(unittest.TestCase):
    """Attribution markers are rejected in the PR title and body only.

    Both halves are asserted. A change that widened the rule to commit messages
    and added content would still pass a test that only checked the rejected
    side, and so would a change that dropped the rule everywhere.
    """

    MARKERS = [
        "Co-Authored-By: Claude <noreply@anthropic.com>",
        "Generated with Claude Code",
        "contact noreply@anthropic.com",
    ]

    def test_rejected_in_title_and_body(self):
        for marker in self.MARKERS:
            with self.subTest(marker=marker):
                self.assertTrue(hh.scan_attribution(marker))
                self.assertTrue(hh.scan_title(marker))
                self.assertTrue(hh.scan_body(f"## Change\n\nRework the parser.\n\n{marker}"))

    def test_still_out_of_scope_for_commit_messages_and_content(self):
        for marker in self.MARKERS:
            with self.subTest(marker=marker):
                self.assertEqual(hh.scan_private_metadata(marker), [])
                self.assertEqual(hh.scan_added_line(marker), [])

    def test_clean_title_and_body_pass(self):
        self.assertEqual(hh.scan_attribution("Generated with the release script"), [])
        self.assertEqual(hh.scan_attribution("Co-Authored-By: Dev <dev@example.com>"), [])
        self.assertEqual(hh.scan_title("ci(hygiene): gate the pull request body"), [])
        self.assertEqual(hh.scan_body(
            "## Change\n\nGate the body pre-submit.\n\nCloses FIR-1234"), [])

    def test_ticket_refs_remain_allowed_alongside_the_new_rule(self):
        # The reversal this file documents must survive the widening above.
        self.assertEqual(hh.scan_title("Gate the body (FIR-1234)"), [])
        self.assertEqual(hh.scan_body("Closes FIR-1234\nCloses FIR-5678"), [])


class SquashTextDashes(unittest.TestCase):
    """Typographic dashes are rejected in the PR title and body only.

    Both halves are asserted. A rule widened to commit messages and added
    content would still pass a test that only checked the rejected side, and so
    would a rule that had been dropped everywhere.
    """

    EM = "\u2014"
    EN = "\u2013"

    def _git_must_not_run(self, *_args, **_kwargs):
        raise AssertionError("text-only mode touched a Git repository")

    def _run(self, title, body):
        with mock.patch.object(hh, "_git", self._git_must_not_run):
            output = io.StringIO()
            with contextlib.redirect_stdout(output):
                result = hh.main([
                    "--no-commits", "--no-content",
                    "--title", title, "--body", body,
                ])
        return result, output.getvalue()

    def test_detects_both_dashes(self):
        self.assertEqual(hh.scan_dashes(f"a {self.EM} b"), ["em dash (U+2014)"])
        self.assertEqual(hh.scan_dashes(f"a {self.EN} b"), ["en dash (U+2013)"])

    def test_hyphens_are_not_dashes(self):
        # The rule is about the typographic characters alone. A gate that also
        # caught these would reject nearly every correct title in the fleet.
        self.assertEqual(hh.scan_dashes("pre-submit mint check"), [])
        self.assertEqual(hh.scan_dashes("run the gate -- then merge"), [])
        self.assertEqual(hh.scan_dashes("window 2026-08-05"), [])

    def test_title_dash_is_refused(self):
        result, printed = self._run(f"Gate the body {self.EM} pre-submit",
                                    "Adds the check.\n\nCloses FIR-1234")
        self.assertEqual(result, 1)
        self.assertIn("PR title contains a typographic dash: em dash (U+2014)",
                      printed)

    def test_body_dash_is_refused(self):
        result, printed = self._run(
            "Gate the body pre-submit",
            f"Adds the check {self.EM} and its tests.\n\nCloses FIR-1234")
        self.assertEqual(result, 1)
        self.assertIn("PR body contains a typographic dash: em dash (U+2014)",
                      printed)

    def test_en_dash_is_refused_too(self):
        result, printed = self._run("Gate the body pre-submit",
                                    f"Covers 2026{self.EN}2027.")
        self.assertEqual(result, 1)
        self.assertIn("PR body contains a typographic dash: en dash (U+2013)",
                      printed)

    def test_clean_title_and_body_pass(self):
        result, printed = self._run(
            "ci(hygiene): refuse typographic dashes in pull request text",
            "## Change\n\nThe gate refuses a dash where the queue mints the "
            "squash message from this text.\n\nCloses FIR-1234")
        self.assertEqual(result, 0)
        self.assertIn("OK: no private reference violations found.", printed)
        self.assertIn(
            "dashes           : em and en dashes rejected in the title and body",
            printed)

    def test_still_out_of_scope_for_commit_messages_and_content(self):
        written = f"rework the parser {self.EM} again"
        self.assertEqual(hh.scan_private_metadata(written), [])
        self.assertEqual(hh.scan_added_line(written), [])
        self.assertEqual(hh.scan_branch_name(f"fix/parser{self.EM}rework"), [])


class TextOnlyMode(unittest.TestCase):
    """``--no-commits --no-content`` runs the pre-submit gate with no Git access.

    The pre-submit surface must never need a checkout of the pull request's own
    code to judge its title and body.
    """

    def _git_must_not_run(self, *_args, **_kwargs):
        raise AssertionError("text-only mode touched a Git repository")

    def test_planted_body_reds_without_touching_git(self):
        with mock.patch.object(hh, "_git", self._git_must_not_run):
            output = io.StringIO()
            with contextlib.redirect_stdout(output):
                result = hh.main([
                    "--no-commits", "--no-content",
                    "--title", "Release Kin v0.5.1",
                    "--body", "Ships the release.\n\n"
                              "https://claude.ai/code/session_0123456789abcdef01",
                ])
            printed = output.getvalue()
        self.assertEqual(result, 1)
        self.assertIn("PR body contains private assistant-session metadata", printed)

    def test_clean_body_greens_without_touching_git(self):
        with mock.patch.object(hh, "_git", self._git_must_not_run):
            output = io.StringIO()
            with contextlib.redirect_stdout(output):
                result = hh.main([
                    "--no-commits", "--no-content",
                    "--title", "Release Kin v0.5.1",
                    "--body", "Ships the release.\n\nCloses FIR-1234",
                ])
            printed = output.getvalue()
        self.assertEqual(result, 0)
        self.assertIn("OK: no private reference violations found.", printed)

    def test_skipped_commit_scan_does_not_report_as_zero_commits(self):
        # `commits scanned : 0` is what an empty range prints. A reader must be
        # able to tell "inspected nothing" from "found nothing".
        with mock.patch.object(hh, "_git", self._git_must_not_run):
            output = io.StringIO()
            with contextlib.redirect_stdout(output):
                hh.main(["--no-commits", "--no-content", "--title", "Add a parser"])
            printed = output.getvalue()
        self.assertIn("commits scanned  : <skipped>", printed)
        self.assertNotIn("commits scanned  : 0", printed)


if __name__ == "__main__":
    unittest.main()
