#!/usr/bin/env python3
"""Unit tests for the public metadata safety gate.

Run with: ``python3 -m unittest discover -s scripts -p 'test_*.py'``

Covers the pure detectors with no git / network access. This exact file is
excluded from the gate's own content scan because it intentionally contains
the very patterns the gate rejects.
"""
import contextlib
import importlib.util
import io
import unittest
from unittest import mock
from pathlib import Path


def _load(name, filename):
    path = Path(__file__).resolve().parent / filename
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


hh = _load("history_hygiene", "history-hygiene.py")


class PrivateMetadata(unittest.TestCase):
    def test_detects_session_trailer(self):
        self.assertTrue(hh.scan_private_metadata("fix bug\n\nClaude-Session: https://x/y"))
        self.assertTrue(hh.scan_private_metadata("Codex-Session: abc"))

    def test_detects_assistant_url_and_session_id(self):
        self.assertTrue(
            hh.scan_private_metadata("see https://claude.ai/code/session_0123456789abcdef01"))
        self.assertTrue(
            hh.scan_private_metadata("see https://chatgpt.com/share/0123456789abcdef"))
        self.assertTrue(hh.scan_private_metadata("ref session_0123456789abcdefAB"))

    def test_clean_message_passes(self):
        self.assertEqual(hh.scan_private_metadata("fix: handle empty input in parser"), [])
        self.assertEqual(hh.scan_private_metadata("Signed-off-by: Dev <dev@example.com>"), [])

    def test_former_authorship_markers_are_out_of_scope(self):
        self.assertEqual(hh.scan_private_metadata(
            "Co-authored-by: Claude <noreply@anthropic.com>"), [])
        self.assertEqual(hh.scan_private_metadata("Generated by Codex"), [])
        self.assertEqual(hh.scan_private_metadata("🤖 Generated with Claude Code"), [])
        self.assertEqual(hh.scan_private_metadata("AI-Generated-by: Copilot"), [])
        self.assertEqual(hh.scan_private_metadata("Assisted-by: ChatGPT"), [])


class TicketRefs(unittest.TestCase):
    def test_detects_fir_and_linear(self):
        self.assertIn("internal ticket ref (FIR-...)", hh.scan_ticket_refs("see FIR-1234 for context"))
        self.assertIn("internal tracker link (linear.app)",
                      hh.scan_ticket_refs("https://linear.app/firelock-ai/issue/abc"))

    def test_clean_text_passes(self):
        self.assertEqual(hh.scan_ticket_refs("ordinary changelog text, no refs"), [])
        # A bare word that merely contains the letters must not match.
        self.assertEqual(hh.scan_ticket_refs("CONFIRMED and AFFIRMED"), [])


class BranchAndTitle(unittest.TestCase):
    def test_branch_private_references(self):
        self.assertTrue(hh.scan_branch_name("troy/fir-1015-consistent-release"))
        self.assertTrue(hh.scan_branch_name("linear.app/firelock-ai/issue/abc"))
        self.assertTrue(hh.scan_branch_name("fix/session_0123456789abcdef"))

    def test_clean_branch_passes(self):
        self.assertEqual(hh.scan_branch_name("ci/public-history-hygiene"), [])
        self.assertEqual(hh.scan_branch_name("automation/kin-registry-dependency-wave"), [])

    def test_title_leaks(self):
        self.assertTrue(hh.scan_title("Fix parser (FIR-1234)"))
        self.assertTrue(hh.scan_title(
            "See https://linear.app/firelock-ai/issue/abc"))
        self.assertTrue(hh.scan_title(
            "See https://chatgpt.com/share/0123456789abcdef"))

    def test_clean_title_passes(self):
        self.assertEqual(hh.scan_title("ci(version-gate): scope bump requirement"), [])

    def test_body_leaks(self):
        self.assertTrue(hh.scan_body(
            "## Change\n\nRework the parser.\n\n"
            "Claude-Session: https://claude.ai/code/session_0123456789abcdef01"))
        self.assertTrue(hh.scan_body("Closes FIR-1965"))
        self.assertTrue(hh.scan_body(
            "Tracked at https://linear.app/firelock-ai/issue/abc"))

    def test_clean_body_passes(self):
        self.assertEqual(hh.scan_body(
            "## Change\n\nHandle empty input at the parser boundary.\n\n"
            "## Acceptance\n\npython3 -m unittest discover -s scripts"), [])
        self.assertEqual(hh.scan_body(""), [])
        self.assertEqual(hh.scan_body(None), [])

    def test_body_names_the_squash_mechanism(self):
        # A captain reading a red check has to learn why a PR body is subject to
        # a commit-message rule, or the fix looks arbitrary and gets bypassed.
        reasons = hh.scan_body("Closes FIR-1965")
        self.assertEqual(len(reasons), 1)
        self.assertIn("minted verbatim into the squash commit message", reasons[0])

    def test_hand_composed_squash_message_drops_only_the_tracker_rule(self):
        # A repository whose squash message is written by a human at the merge
        # button does not publish its PR body, so the tracker-ref rule does not
        # apply. Assistant-session references stay barred: a PR body is a
        # published artifact whether or not it becomes a commit.
        self.assertEqual(hh.scan_body("Closes FIR-1965", is_squash_source=False), [])
        self.assertTrue(hh.scan_body(
            "Claude-Session: https://claude.ai/code/session_0123456789abcdef01",
            is_squash_source=False))


class AddedLineContent(unittest.TestCase):
    def test_detects_refs_and_traces(self):
        self.assertTrue(hh.scan_added_line("// TODO see FIR-9001"))
        self.assertTrue(hh.scan_added_line("# Claude-Session: zzz"))

    def test_clean_code_passes(self):
        self.assertEqual(hh.scan_added_line("let total = a + b; // sum"), [])
        self.assertEqual(hh.scan_added_line("// Generated by a code assistant"), [])


class Excludes(unittest.TestCase):
    def test_default_excludes(self):
        ex = hh.DEFAULT_CONTENT_EXCLUDES
        self.assertTrue(hh.is_excluded("scripts/history-hygiene.py", ex))
        self.assertTrue(hh.is_excluded("scripts/test_history_hygiene.py", ex))

    def test_source_not_excluded(self):
        ex = hh.DEFAULT_CONTENT_EXCLUDES
        self.assertFalse(hh.is_excluded("src/lib.rs", ex))
        self.assertFalse(hh.is_excluded("README.md", ex))
        self.assertFalse(hh.is_excluded(".github/workflows/ci.yml", ex))
        self.assertFalse(hh.is_excluded("CHANGELOG.md", ex))
        self.assertFalse(hh.is_excluded("Cargo.lock", ex))


class GitPlumbing(unittest.TestCase):
    @mock.patch.object(hh.subprocess, "run")
    def test_git_errors_fail_closed(self, run):
        run.return_value = mock.Mock(
            returncode=128,
            stdout="",
            stderr="fatal: bad revision 'missing'",
        )

        with self.assertRaisesRegex(RuntimeError, "bad revision"):
            hh._git(["log", "missing"])

    def test_commit_message_control_separators_cannot_skip_scan(self):
        # The old record/field separators were legal commit-message bytes.
        # NUL is not, so attacker-controlled message bytes cannot forge a
        # record boundary in the scanner's Git format.
        self.assertEqual(hh._REC, "\0\0")
        self.assertEqual(hh._FLD, "\0")

    @mock.patch.object(hh, "_git")
    def test_commit_format_uses_git_nul_escapes_not_argv_nuls(self, git):
        git.return_value = mock.Mock(stdout="")

        self.assertEqual(hh.collect_commits("base", "head"), [])

        args = git.call_args.args[0]
        format_arg = next(arg for arg in args if arg.startswith("--format="))
        self.assertIn("%x00", format_arg)
        self.assertNotIn("\0", format_arg)
        for identity_field in ("%an", "%ae", "%cn", "%ce", "%ct"):
            self.assertNotIn(identity_field, format_arg)


class LegacyOptions(unittest.TestCase):
    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "Generated by a code assistant"}])
    def test_timestamp_option_is_accepted_and_ignored(self, _commits, _lines):
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main([
                "--check-timestamps",
                "--bot-email", "bot@example.com",
                "--tz", "America/New_York",
                "--window-start", "9",
                "--window-end", "18",
            ])
        self.assertEqual(result, 0)
        self.assertIn("legacy timestamp option: ignored", output.getvalue())


class PolicyIntegration(unittest.TestCase):
    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "See FIR-123"}])
    def test_commit_message_tracker_ref_fails(self, _commits, _lines):
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main([])
        self.assertEqual(result, 1)
        self.assertIn("internal tracker metadata", output.getvalue())

    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "add a parser"}])
    def test_body_leak_fails_while_every_commit_is_clean(self, _commits, _lines):
        # The shape of the defect: branch commits, title, and content all pass,
        # and the leak reaches public history through the minted squash alone.
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main([
                "--title", "Add a parser",
                "--body", "Adds a parser.\n\n"
                          "Claude-Session: https://claude.ai/code/session_0123456789abcdef01",
            ])
        self.assertEqual(result, 1)
        self.assertIn("PR body contains private assistant-session metadata",
                      output.getvalue())

    @mock.patch.object(hh, "collect_added_lines", return_value=[])
    @mock.patch.object(hh, "collect_commits",
                       return_value=[{"sha": "abc123", "body": "add a parser"}])
    def test_absent_body_is_reported_as_unscanned_not_as_clean(self, _commits, _lines):
        # A gate that reports the same thing whether it read an input or never
        # received one cannot be audited. This is the line that would have shown
        # the blind spot at a glance.
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            result = hh.main(["--title", "Add a parser"])
        self.assertEqual(result, 0)
        self.assertIn("body             : <none supplied, not scanned>", output.getvalue())

        scanned = io.StringIO()
        with contextlib.redirect_stdout(scanned):
            hh.main(["--title", "Add a parser", "--body", "Adds a parser."])
        self.assertIn("body             : 14 chars scanned as the squash message",
                      scanned.getvalue())


if __name__ == "__main__":
    unittest.main()
