"""Tests for kin-actions self-release planning and generated bytes."""

from __future__ import annotations

import importlib.util
import os
import stat
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


def load(name: str, filename: str):
    path = Path(__file__).with_name(filename)
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


prepare = load("prepare_self_release", "prepare-self-release.py")
planner = load("plan_self_release", "plan-self-release.py")


class SelfReleasePlannerTests(unittest.TestCase):
    def test_shipped_workflows_scripts_actions_and_manifest_release(self) -> None:
        for path in (
            ".github/workflows/cargo-registry-release.yml",
            ".github/actions/example/action.yml",
            ".kin-release/consumers.json",
            "scripts/update-cargo-registry-deps.py",
            "scripts/publish-crate.sh",
        ):
            with self.subTest(path=path):
                self.assertTrue(planner.is_release_affecting(path))

    def test_docs_version_and_tests_do_not_release(self) -> None:
        for path in (
            "README.md",
            "CONTRIBUTING.md",
            "VERSION",
            "docs/design.md",
            "scripts/test_release_workflow.py",
            ".github/ISSUE_TEMPLATE/bug.yml",
        ):
            with self.subTest(path=path):
                self.assertFalse(planner.is_release_affecting(path))

    def test_plan_deduplicates_release_paths(self) -> None:
        result = planner.plan(
            ["README.md", "scripts/tool.py", "scripts/tool.py"],
            "minor",
        )
        self.assertTrue(result["release_needed"])
        self.assertEqual(result["release_paths"], ["scripts/tool.py"])
        self.assertEqual(result["intent"], "minor")


class SelfReleasePreparationTests(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        (self.root / "VERSION").write_text("0.1.22\n", encoding="utf-8")
        self.readme = self.root / "README.md"
        self.contributing = self.root / "CONTRIBUTING.md"
        self.readme.write_text(
            "uses: firelock-ai/kin-actions/.github/workflows/"
            "cargo-registry-release.yml@v0.1.22\n",
            encoding="utf-8",
        )
        self.contributing.write_text(
            "uses: firelock-ai/kin-actions/.github/workflows/"
            "public-history-hygiene.yml@v0.1.8\n",
            encoding="utf-8",
        )

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def prepare_release(self, intent: str = "patch"):
        return prepare.prepare_self_release(
            root=self.root,
            base_version="0.1.22",
            intent=intent,
        )

    def git(self, *args: str) -> str:
        return subprocess.run(
            ["git", *args],
            cwd=self.root,
            text=True,
            capture_output=True,
            check=True,
        ).stdout.strip()

    def commit_base(self) -> str:
        self.git("init", "-q")
        self.git("config", "user.name", "Fixture")
        self.git("config", "user.email", "fixture@example.invalid")
        self.git("config", "core.hooksPath", "/dev/null")
        self.git("add", ".")
        self.git("commit", "-q", "-m", "base")
        return self.git("rev-parse", "HEAD")

    def test_patch_updates_version_and_all_doc_pins(self) -> None:
        result = self.prepare_release()
        self.assertEqual((self.root / "VERSION").read_text(), "0.1.23\n")
        self.assertIn("@v0.1.23", self.readme.read_text())
        self.assertIn("@v0.1.23", self.contributing.read_text())
        self.assertEqual(
            result["generated_paths"],
            ["CONTRIBUTING.md", "README.md", "VERSION"],
        )

    def test_semver_minor_major_and_zero_to_one(self) -> None:
        self.assertEqual(
            prepare.choose_target("0.1.22", "0.1.22", "minor"), "0.2.0"
        )
        self.assertEqual(
            prepare.choose_target("0.1.22", "0.1.22", "major"), "1.0.0"
        )

    def test_existing_higher_intent_is_never_downgraded(self) -> None:
        (self.root / "VERSION").write_text("0.2.0\n", encoding="utf-8")
        result = self.prepare_release("patch")
        self.assertEqual(result["target_version"], "0.2.0")

    def test_arbitrary_version_and_prerelease_fail(self) -> None:
        for current in ("0.1.27", "0.1.22-rc.1"):
            with self.subTest(current=current):
                (self.root / "VERSION").write_text(current + "\n", encoding="utf-8")
                with self.assertRaises(prepare.SelfReleaseError):
                    self.prepare_release()

    def test_newer_doc_pin_fails_before_any_write(self) -> None:
        self.readme.write_text(
            "firelock-ai/kin-actions/.github/workflows/x.yml@v9.0.0\n",
            encoding="utf-8",
        )
        before = (self.root / "VERSION").read_bytes()
        with self.assertRaisesRegex(prepare.SelfReleaseError, "downgrade"):
            self.prepare_release()
        self.assertEqual((self.root / "VERSION").read_bytes(), before)

    def test_symlink_doc_fails_closed(self) -> None:
        self.readme.unlink()
        os.symlink(self.contributing, self.readme)
        with self.assertRaisesRegex(prepare.SelfReleaseError, "regular file"):
            self.prepare_release()

    def test_modes_are_preserved(self) -> None:
        self.readme.chmod(0o640)
        self.prepare_release()
        self.assertEqual(stat.S_IMODE(self.readme.stat().st_mode), 0o640)

    def test_verifier_accepts_exact_reconstructed_bytes_and_modes(self) -> None:
        base = self.commit_base()
        self.prepare_release()
        self.git("add", ".")
        self.git("commit", "-q", "-m", "release")

        result = prepare.verify_self_release(
            root=self.root,
            base_ref=base,
            base_version="0.1.22",
            target_version="0.1.23",
            generated_paths=["CONTRIBUTING.md", "README.md", "VERSION"],
        )
        self.assertEqual(
            result["verified_paths"],
            ["CONTRIBUTING.md", "README.md", "VERSION"],
        )

    def test_verifier_rejects_allowlisted_content_injection(self) -> None:
        base = self.commit_base()
        self.prepare_release()
        self.readme.write_text(
            self.readme.read_text(encoding="utf-8") + "injected\n",
            encoding="utf-8",
        )
        self.git("add", ".")
        self.git("commit", "-q", "-m", "malicious release")

        with self.assertRaisesRegex(
            prepare.SelfReleaseError, "deterministic bytes"
        ):
            prepare.verify_self_release(
                root=self.root,
                base_ref=base,
                base_version="0.1.22",
                target_version="0.1.23",
                generated_paths=["CONTRIBUTING.md", "README.md", "VERSION"],
            )

    def test_verifier_rejects_allowlisted_mode_change(self) -> None:
        base = self.commit_base()
        self.prepare_release()
        self.readme.chmod(0o755)
        self.git("add", ".")
        self.git("commit", "-q", "-m", "mode injection")

        with self.assertRaisesRegex(
            prepare.SelfReleaseError, "mode changed"
        ):
            prepare.verify_self_release(
                root=self.root,
                base_ref=base,
                base_version="0.1.22",
                target_version="0.1.23",
                generated_paths=["CONTRIBUTING.md", "README.md", "VERSION"],
            )


if __name__ == "__main__":
    unittest.main()
